Allow releaseinfo changes on RPis (CU-1kxmhta)
bravetechnologycoop/BraveButtons pull request #124
Opened 2021-11-01 21:52 UTC by trisapeace

- Raspian OS version has changed from Buster to something else. So now,
  Buster, the one that is on our devices, is considered `oldstable`
  instead of `stable`. This fix came from:
  https://forums.raspberrypi.com/viewtopic.php?t=318302

# Test Plan
- :heavy_check_mark: Run `apt update --allow-releaseinfo-change` manually on the Kye7e hub just to make sure that it works with `apt update` (when we did this during the last deployment, we used `apt-get update`)
- :heavy_check_mark: Make these change to `setup_pi.sh` file on Alvis 1R Hub (which was missed during the previous deployment because it was offline at the time) and manually run `sudo ./BraveButtons/pi/setup_pi.sh ./BraveButtons/pi/pi_config.ini` to make sure that the changes to the script will work
- :heavy_check_mark: Run the Ansible script on just Alvis 1R to make sure that it will work for subsequent deployment (`ansible-playbook -i ~/BraveButtonsConfig/ansible/inventory-prod.yaml  ~/BraveButtons/ops/update_pi_fleet.yaml --ask-vault-pass --limit alvis_pi_1R`)

2021-11-01 21:52 UTC, trisapeace commented
Task linked: [CU-1kxmhta update RPi setup script to allow release info changes](https://app.clickup.com/t/1kxmhta)

2021-11-02 01:44 UTC, schwarrrtz commented
looks great. thanks for updating the pairing tool as well.

2021-11-02 01:45 UTC, schwarrrtz requested changes
can you update the changelog?

2021-11-02 15:47 UTC, trisapeace commented
@schwarrrtz , good catch. CHANGELOG now updated.

2021-11-02 17:04 UTC, schwarrrtz approved these changes
looks great.

2021-11-02 19:29 UTC, merged