Update Dashboard (CU-86du23zth)
bravetechnologycoop/BraveButtons pull request #246
Opened 2024-08-29 20:03 UTC by Darrickg

couple things:
- still need to do test cases
- separated new buttons into a different task
- if location id is still blank, it will break because of validator. so corey pls work on that task first
- still need to clean up my code

will merge once i do the test cases but for now micah please review to see im doing everything correctly

2024-08-29 20:03 UTC, trisapeace commented
Task linked: [CU-86du23zth Make the buttons dashboard more useful](https://app.clickup.com/t/86du23zth)

2024-08-29 23:04 UTC, micahdbak approved these changes
👍 

feel free to merge without test cases

2024-10-10 16:44 UTC, Darrickg commented
@johnny-brave finally done, you can test!

2024-10-17 20:04 UTC, Nakul727 commented on server/mustache-templates/clientPage.mst
> +    <title>Brave Sensor Dashboard</title>
* Buttons

2024-10-17 20:15 UTC, Nakul727 requested changes
Have tested the dashboard to my best and everything works perfectly! Good job 👍Just a few minor changes I have annotated for change. 

Along with that a small cases of error handling should be added if invalid gateway id (not uuid) is inputed. It gives a 500 error, shows blank screen but logs the error in server. Maybe add check to handle this.

Otherwise good from my side, everything works!!

2024-10-17 20:15 UTC, Nakul727 commented on server/mustache-templates/newGateway.mst
> +                        <label for="gatewayId" class="col-sm-3 col-form-label"></label>
Add label for gateway id

2024-10-17 20:15 UTC, Nakul727 commented on server/mustache-templates/clientPage.mst
> +    <title>Brave Sensor Dashboard</title>
Also check title headers for the other pages

2024-10-18 21:30 UTC, Darrickg commented on server/mustache-templates/newGateway.mst
> +                        <label for="gatewayId" class="col-sm-3 col-form-label"></label>
fixed in latest push

2024-10-18 22:50 UTC, Nakul727 approved these changes
Looks good to me, amazing work! Wait on @johnny-brave to review and test and should be ready to merge :))

2024-10-22 00:24 UTC, johnny-brave approved these changes
Very impressive work! Thanks for taking on such a big task, this will be really helpful for future provisioning. I've tested all the functionalities of the dashboard with real dev devices and everything is working correctly. The only thing I noticed is that this says 'Radar Particle Core ID' when it should say 'Serial Number'. Please make that change
![image](https://github.com/user-attachments/assets/962f8e29-2657-458f-8e11-99c3b469d34e)
 Other than that, If Nakul approves of the code, then it's ready to merge.

2024-10-22 18:01 UTC, merged