Added Sentry for aggregating and tracking errors and outages (CU-32a5wb)
bravetechnologycoop/BraveButtons pull request #93
Opened 2021-04-30 18:11 UTC by mariocimet

2021-04-30 21:16 UTC, trisapeace approved these changes

2021-04-30 21:45 UTC, mariocimet commented on server/.env.example
> +ENIRONMENT=exampleenvironment
fixed.

2021-05-01 00:41 UTC, trisapeace approved these changes
Cool. Re-approved.

2021-05-03 19:01 UTC, schwarrrtz requested changes
@mariocimet it looks like you added a `package-lock.json` in the root directory of the repo, this is probably a mistake?

2021-05-03 19:22 UTC, schwarrrtz commented
I ran `npm ci` and then ran the tests locally (using a local Postgres db) and everything passes for me. Once that extra file is removed I'd say this is good to go.

2021-05-04 19:27 UTC, mariocimet commented
> @mariocimet it looks like you added a `package-lock.json` in the root directory of the repo, this is probably a mistake? Otherwise this looks great, I'm just finishing up reviewing the changes

done!

2021-05-06 19:32 UTC, schwarrrtz approved these changes

2021-05-13 20:32 UTC, trisapeace approved these changes

2021-05-13 22:17 UTC, merged